# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credential.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("credential.proto", :syntax => :proto3) do
    add_message "pb.Credential" do
      optional :domain, :string, 1
      optional :access_token, :string, 2
    end
  end
end

module Pb
  Credential = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Credential").msgclass
end
