# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order.proto", :syntax => :proto3) do
    add_message "pb.Order" do
      optional :order, :message, 1, "pb.OrderDetail"
    end
    add_message "pb.OrderDetail" do
      optional :id, :uint64, 1
      optional :email, :string, 2
      optional :closed_at, :string, 3
      optional :created_at, :string, 4
      optional :updated_at, :string, 5
      optional :number, :uint64, 6
      optional :note, :string, 7
      optional :token, :string, 8
      optional :gateway, :string, 9
      optional :test, :bool, 10
      optional :total_price, :string, 11
      optional :subtotal_price, :string, 12
      optional :total_weight, :uint32, 14
      optional :total_tax, :string, 15
      optional :taxes_included, :bool, 16
      optional :currency, :string, 17
      optional :financial_status, :string, 18
      optional :confirmed, :bool, 19
      optional :total_discounts, :string, 20
      optional :total_line_items_price, :string, 21
      optional :cart_token, :string, 22
      optional :buyer_accepts_marketing, :bool, 32
      optional :name, :string, 33
      optional :referring_site, :string, 34
      optional :landing_site, :string, 35
      optional :cancelled_at, :string, 36
      optional :cancel_reason, :string, 37
      optional :total_price_usd, :string, 38
      optional :checkout_token, :string, 39
      optional :reference, :string, 40
      optional :user_id, :uint64, 41
      optional :location_id, :uint64, 42
      optional :source_identifier, :string, 43
      optional :source_url, :string, 44
      optional :processed_at, :string, 45
      optional :phone, :string, 46
      optional :customer_locale, :string, 47
      optional :app_id, :uint64, 48
      optional :browser_ip, :string, 49
      optional :landing_site_ref, :string, 50
      optional :order_number, :uint64, 51
      repeated :discount_applications, :message, 52, "pb.OrderDetail.DiscountApplication"
      repeated :discount_codes, :message, 53, "pb.OrderDetail.DiscountCode"
      repeated :note_attributes, :message, 54, "pb.OrderDetail.NoteAttribute"
      repeated :payment_gateway_names, :string, 55
      optional :processing_method, :string, 56
      optional :checkout_id, :uint64, 57
      optional :source_name, :uint64, 58
      optional :fulfillment_status, :string, 59
      repeated :tax_lines, :message, 60, "pb.OrderDetail.TaxLine"
      optional :tags, :string, 61
      optional :contact_email, :string, 62
      optional :order_status_url, :string, 63
      optional :presentment_currency, :string, 64
      optional :total_line_items_price_set, :message, 65, "pb.OrderDetail.TotalLineItemsPriceSet"
      optional :total_discounts_set, :message, 66, "pb.OrderDetail.TotalDiscountsSet"
      optional :total_shipping_price_set, :message, 67, "pb.OrderDetail.TotalShippingPriceSet"
      optional :subtotal_price_set, :message, 68, "pb.OrderDetail.SubTotalPriceSet"
      optional :total_price_set, :message, 69, "pb.OrderDetail.TotalPriceSet"
      optional :total_tax_set, :message, 70, "pb.OrderDetail.TotalTaxSet"
      repeated :line_items, :message, 71, "pb.OrderDetail.LineItem"
      repeated :fulfillments, :message, 72, "pb.OrderDetail.Fulfillment"
      repeated :refunds, :message, 73, "pb.OrderDetail.Refund"
      optional :total_tip_received, :string, 74
      optional :original_total_duties_set, :message, 76, "pb.OrderDetail.OriginalTotalDutiesSet"
      optional :current_total_duties_set, :message, 77, "pb.OrderDetail.CurrentTotalDutiesSet"
      optional :admin_graphql_api_id, :string, 78
      repeated :shipping_lines, :message, 79, "pb.OrderDetail.ShippingLine"
      optional :shipping_address, :message, 80, "pb.OrderDetail.ShippingAddress"
      optional :customer, :message, 81, "pb.OrderDetail.Customer"
      optional :device_id, :uint64, 82
    end
    add_message "pb.OrderDetail.DiscountApplication" do
      optional :type, :string, 1
      optional :title, :string, 2
      optional :description, :string, 3
      optional :value, :string, 4
      optional :value_type, :string, 5
      optional :allocation_method, :string, 6
      optional :target_selection, :string, 7
      optional :target_type, :string, 8
    end
    add_message "pb.OrderDetail.TaxLine" do
      optional :title, :string, 1
      optional :price, :string, 2
      optional :rate, :float, 3
      optional :price_set, :message, 4, "pb.OrderDetail.PriceSet"
      optional :total_discount_set, :message, 5, "pb.OrderDetail.TotalDiscountsSet"
    end
    add_message "pb.OrderDetail.PriceSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.DiscountCode" do
      optional :code, :string, 1
      optional :amount, :string, 2
      optional :type, :string, 3
    end
    add_message "pb.OrderDetail.NoteAttribute" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "pb.OrderDetail.TotalLineItemsPriceSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.TotalDiscountsSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.TotalShippingPriceSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.SubTotalPriceSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.TotalPriceSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.TotalTaxSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.LineItem" do
      optional :id, :uint64, 1
      optional :variant_id, :uint64, 2
      optional :quantity, :uint32, 3
      optional :sku, :string, 4
      optional :variant_title, :string, 5
      optional :vendor, :string, 6
      optional :fulfillment_service, :string, 7
      optional :product_id, :uint64, 8
      optional :taxable, :bool, 9
      optional :gift_card, :bool, 10
      optional :name, :string, 11
      optional :variant_inventory_management, :string, 12
      repeated :properties, :message, 13, "pb.OrderDetail.Property"
      optional :product_exists, :bool, 14
      optional :fulfillable_quantity, :uint32, 15
      optional :grams, :uint32, 16
      optional :price, :string, 17
      optional :total_discount, :string, 18
      optional :fulfillment_status, :string, 19
      optional :price_set, :message, 20, "pb.OrderDetail.PriceSet"
      optional :total_discount_set, :message, 21, "pb.OrderDetail.TotalDiscountsSet"
      repeated :discount_allocations, :message, 22, "pb.OrderDetail.LineItem.DiscountAllocation"
      repeated :duties, :message, 23, "pb.OrderDetail.Duty"
      optional :admin_graphql_api_id, :string, 24
      repeated :tax_lines, :message, 25, "pb.OrderDetail.TaxLine"
      optional :requires_shipping, :bool, 26
      optional :title, :string, 27
    end
    add_message "pb.OrderDetail.LineItem.DiscountAllocation" do
      optional :amount, :string, 1
      optional :discount_application_index, :uint32, 2
      optional :amount_set, :message, 3, "pb.OrderDetail.LineItem.DiscountAllocation.AmountSet"
    end
    add_message "pb.OrderDetail.LineItem.DiscountAllocation.AmountSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.Fulfillment" do
      optional :created_at, :string, 1
      optional :id, :uint64, 2
      optional :order_id, :uint64, 3
      optional :status, :string, 4
      optional :tracking_company, :string, 5
      optional :tracking_number, :string, 6
      optional :updated_at, :string, 7
    end
    add_message "pb.OrderDetail.Refund" do
      optional :id, :uint64, 1
      optional :order_id, :uint64, 2
      optional :created_at, :string, 3
      optional :note, :string, 4
      optional :user_id, :uint64, 5
      optional :processed_at, :string, 6
      repeated :refund_item_lines, :message, 7, "pb.OrderDetail.Refund.RefundItemLine"
    end
    add_message "pb.OrderDetail.Refund.RefundItemLine" do
      optional :line_item_id, :uint64, 1
      optional :quantity, :uint32, 2
    end
    add_message "pb.OrderDetail.OriginalTotalDutiesSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.CurrentTotalDutiesSet" do
      optional :shop_money, :message, 1, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 2, "pb.OrderDetail.PresentmentMoney"
    end
    add_message "pb.OrderDetail.ShippingLine" do
      optional :code, :string, 1
      optional :price, :string, 2
      optional :title, :string, 3
    end
    add_message "pb.OrderDetail.ShippingAddress" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
      optional :address1, :string, 3
      optional :phone, :string, 4
      optional :city, :string, 5
      optional :zip, :string, 6
      optional :province, :string, 7
      optional :country, :string, 8
      optional :address2, :string, 9
      optional :company, :string, 10
      optional :latitude, :float, 11
      optional :longitude, :float, 12
      optional :name, :string, 13
      optional :country_code, :string, 14
      optional :province_code, :string, 15
    end
    add_message "pb.OrderDetail.Customer" do
      optional :id, :uint64, 1
      optional :email, :string, 2
      optional :accepts_marketing, :bool, 3
      optional :created_at, :string, 4
      optional :updated_at, :string, 5
      optional :first_name, :string, 6
      optional :last_name, :string, 7
      optional :orders_count, :uint32, 8
      optional :state, :string, 9
      optional :total_spent, :string, 10
      optional :last_order_id, :uint64, 12
      optional :note, :string, 13
      optional :verified_email, :bool, 14
      optional :multipass_identifier, :string, 15
      optional :tax_exempt, :bool, 16
      optional :phone, :string, 17
      optional :tags, :string, 18
      optional :last_order_name, :string, 19
      optional :currency, :string, 20
      optional :accepts_marketing_updated_at, :string, 21
      optional :marketing_opt_in_level, :string, 22
      optional :admin_graphql_api_id, :string, 23
      optional :default_address, :message, 24, "pb.OrderDetail.Customer.DefaultAddress"
      repeated :tax_exemptions, :string, 25
    end
    add_message "pb.OrderDetail.Customer.DefaultAddress" do
      optional :id, :uint64, 1
      optional :customer_id, :uint64, 2
      optional :first_name, :string, 3
      optional :last_name, :string, 4
      optional :company, :string, 5
      optional :zip, :string, 6
      optional :phone, :string, 7
      optional :name, :string, 8
      optional :province_code, :string, 9
      optional :country_code, :string, 10
      optional :country_name, :string, 11
      optional :default, :bool, 12
      optional :address1, :string, 13
      optional :address2, :string, 14
      optional :city, :string, 15
      optional :province, :string, 16
      optional :country, :string, 17
    end
    add_message "pb.OrderDetail.ShopMoney" do
      optional :amount, :string, 1
      optional :currency_code, :string, 2
    end
    add_message "pb.OrderDetail.PresentmentMoney" do
      optional :amount, :string, 1
      optional :currency_code, :string, 2
    end
    add_message "pb.OrderDetail.Property" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "pb.OrderDetail.Duty" do
      optional :id, :uint64, 1
      optional :harmonize_system_code, :string, 2
      optional :country_code_of_original, :string, 3
      optional :shop_money, :message, 4, "pb.OrderDetail.ShopMoney"
      optional :presentment_money, :message, 5, "pb.OrderDetail.PresentmentMoney"
      repeated :tax_lines, :message, 6, "pb.OrderDetail.TaxLine"
    end
  end
end

module Pb
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Order").msgclass
  OrderDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail").msgclass
  OrderDetail::DiscountApplication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.DiscountApplication").msgclass
  OrderDetail::TaxLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TaxLine").msgclass
  OrderDetail::PriceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.PriceSet").msgclass
  OrderDetail::DiscountCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.DiscountCode").msgclass
  OrderDetail::NoteAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.NoteAttribute").msgclass
  OrderDetail::TotalLineItemsPriceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TotalLineItemsPriceSet").msgclass
  OrderDetail::TotalDiscountsSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TotalDiscountsSet").msgclass
  OrderDetail::TotalShippingPriceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TotalShippingPriceSet").msgclass
  OrderDetail::SubTotalPriceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.SubTotalPriceSet").msgclass
  OrderDetail::TotalPriceSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TotalPriceSet").msgclass
  OrderDetail::TotalTaxSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.TotalTaxSet").msgclass
  OrderDetail::LineItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.LineItem").msgclass
  OrderDetail::LineItem::DiscountAllocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.LineItem.DiscountAllocation").msgclass
  OrderDetail::LineItem::DiscountAllocation::AmountSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.LineItem.DiscountAllocation.AmountSet").msgclass
  OrderDetail::Fulfillment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Fulfillment").msgclass
  OrderDetail::Refund = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Refund").msgclass
  OrderDetail::Refund::RefundItemLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Refund.RefundItemLine").msgclass
  OrderDetail::OriginalTotalDutiesSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.OriginalTotalDutiesSet").msgclass
  OrderDetail::CurrentTotalDutiesSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.CurrentTotalDutiesSet").msgclass
  OrderDetail::ShippingLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.ShippingLine").msgclass
  OrderDetail::ShippingAddress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.ShippingAddress").msgclass
  OrderDetail::Customer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Customer").msgclass
  OrderDetail::Customer::DefaultAddress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Customer.DefaultAddress").msgclass
  OrderDetail::ShopMoney = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.ShopMoney").msgclass
  OrderDetail::PresentmentMoney = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.PresentmentMoney").msgclass
  OrderDetail::Property = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Property").msgclass
  OrderDetail::Duty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderDetail.Duty").msgclass
end
