# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_request.proto

require 'google/protobuf'

require 'credential_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order_request.proto", :syntax => :proto3) do
    add_message "pb.OrderRequest" do
      optional :credential, :message, 1, "pb.Credential"
      optional :path, :message, 2, "pb.OrderRequest.Path"
    end
    add_message "pb.OrderRequest.Path" do
      optional :id, :uint64, 1
    end
  end
end

module Pb
  OrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderRequest").msgclass
  OrderRequest::Path = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.OrderRequest.Path").msgclass
end
