# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_request.proto

require 'google/protobuf'

require 'credential_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product_request.proto", :syntax => :proto3) do
    add_message "pb.ProductRequest" do
      optional :credential, :message, 1, "pb.Credential"
      optional :query, :message, 2, "pb.ProductRequest.Query"
    end
    add_message "pb.ProductRequest.Query" do
      repeated :id, :uint64, 1
    end
  end
end

module Pb
  ProductRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.ProductRequest").msgclass
  ProductRequest::Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.ProductRequest.Query").msgclass
end
