# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product.proto", :syntax => :proto3) do
    add_message "pb.Product" do
      optional :id, :int64, 1
      optional :title, :string, 2
      optional :body_html, :string, 3
      optional :vendor, :string, 4
      optional :product_type, :string, 5
      optional :created_at, :string, 6
      optional :handle, :string, 7
      optional :updated_at, :string, 8
      optional :published_at, :string, 9
      optional :template_suffix, :string, 10
      optional :status, :string, 11
      optional :published_scope, :string, 12
      optional :tags, :string, 13
      optional :admin_graphql_api_id, :string, 14
      repeated :variants, :message, 15, "pb.Product.Variant"
      repeated :options, :message, 16, "pb.Product.Option"
      repeated :images, :message, 17, "pb.Product.Image"
      optional :image, :message, 18, "pb.Product.Image"
    end
    add_message "pb.Product.Variant" do
      optional :id, :int64, 1
      optional :title, :string, 2
      optional :price, :string, 3
      optional :sku, :string, 4
      optional :position, :uint32, 5
      optional :inventory_policy, :string, 6
      optional :compare_at_price, :string, 7
      optional :fulfillment_service, :string, 8
      optional :inventory_management, :string, 9
      optional :option1, :string, 10
      optional :option2, :string, 11
      optional :option3, :string, 12
      optional :created_at, :string, 13
      optional :updated_at, :string, 14
      optional :taxable, :bool, 15
      optional :barcode, :string, 16
      optional :grams, :uint32, 17
      optional :image_id, :int64, 18
      optional :weight, :double, 19
      optional :weight_unit, :string, 20
      optional :inventory_item_id, :int64, 21
      optional :inventory_quantity, :uint32, 22
      optional :old_inventory_quantity, :uint32, 23
      optional :requires_shipping, :bool, 24
      optional :admin_graphql_api_id, :string, 25
      optional :product_id, :uint64, 26
    end
    add_message "pb.Product.Option" do
      optional :id, :uint64, 1
      optional :product_id, :uint64, 2
      optional :name, :string, 3
      optional :position, :uint32, 4
      repeated :values, :string, 5
    end
    add_message "pb.Product.Image" do
      optional :id, :uint64, 1
      optional :position, :uint32, 2
      optional :created_at, :string, 3
      optional :updated_at, :string, 4
      optional :alt, :string, 5
      optional :width, :uint32, 6
      optional :height, :uint32, 7
      optional :src, :string, 8
      repeated :variant_ids, :uint32, 9
      optional :admin_graphql_api_id, :string, 10
      optional :product_id, :uint64, 11
    end
  end
end

module Pb
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Product").msgclass
  Product::Variant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Product.Variant").msgclass
  Product::Option = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Product.Option").msgclass
  Product::Image = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Product.Image").msgclass
end
