# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_request.proto

require 'google/protobuf'

require 'credential_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("products_request.proto", :syntax => :proto3) do
    add_message "pb.ProductsRequest" do
      optional :credential, :message, 1, "pb.Credential"
      optional :query, :message, 2, "pb.ProductsRequest.Query"
    end
    add_message "pb.ProductsRequest.Query" do
      repeated :ids, :uint64, 1
    end
  end
end

module Pb
  ProductsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.ProductsRequest").msgclass
  ProductsRequest::Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.ProductsRequest.Query").msgclass
end
