# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto

require 'google/protobuf'

require 'product_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("products.proto", :syntax => :proto3) do
    add_message "pb.Products" do
      repeated :products, :message, 1, "pb.Product"
    end
  end
end

module Pb
  Products = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Products").msgclass
end
