# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopify_service.proto

require 'google/protobuf'

require 'products_pb'
require 'product_pb'
require 'products_request_pb'
require 'product_request_pb'
require 'order_pb'
require 'order_request_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("shopify_service.proto", :syntax => :proto3) do
  end
end

module Pb
end
