# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: shopify_service.proto for package 'pb'

require 'grpc'
require 'shopify_service_pb'

module Pb
  module Shopify
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pb.Shopify'

      rpc :GetProducts, ::Pb::ProductsRequest, ::Pb::Products
      rpc :GetProduct, ::Pb::ProductRequest, ::Pb::Product
      rpc :GetOrder, ::Pb::OrderRequest, ::Pb::Order
    end

    Stub = Service.rpc_stub_class
  end
end
